apiVersion: v1
kind: Service
metadata:
  name: {{ include "usagely.fullname" . }}-api
  labels:
    {{- include "usagely.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "usagely.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
