apiVersion: v1
kind: Secret
metadata:
  name: {{ include "usagely.fullname" . }}
  labels:
    {{- include "usagely.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.auth.secret | quote }}
  {{- if not .Values.auth.jwksUrl }}
  JWKS_URL: {{ printf "http://%s-web:%d/api/auth/jwks" (include "usagely.fullname" .) (int .Values.web.port) | quote }}
  {{- else }}
  JWKS_URL: {{ .Values.auth.jwksUrl | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  PG_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
  AUTH_SECRET: {{ .Values.auth.secret | quote }}
