version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    staticcheck:
      checks:
        - inherit
        - "-SA1029"
        - "-ST1000"
        - "-ST1003"
        - "-ST1005"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"

  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - unused
